### ISSUE TITLE
Provide local user config file for Vagrant to specify CUP & RAM

### ISSUE THREAD

**Issue by robert4man** [robert4man/vagrant-oucsdev#4]
Allow users the ability to override the vagrant defaults for number of cpu cores and amount of ram to allocate to the vm when provisioning. The local config file should be ignore by git.

**Comment by DavidWisniewski001** [comment]
I would like too take on this issue

**Comment by robert4man** [comment]
Here are some things to help you out:
https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile 

Note the following near the top:
default_config_file = "#{host_drupalvm_dir}/default.config.yml"
unless File.exist?(default_config_file)
  raise_message "Configuration file not found! Expected in #{default_config_file}"
end

vconfig = load_config([
  default_config_file,
  "#{host_config_dir}/local.config.yml"
])

Then he has sections like this for each hypervisor:
  # VirtualBox.
  config.vm.provider :virtualbox do |v|
    v.name = vconfig['vagrant_hostname']
    v.memory = vconfig['vagrant_memory']
    v.cpus = vconfig['vagrant_cpus']
end

Then combine this idea with the work @jball2020 did for #3 and we'll have a single global config file for both Vagrant and Ansible which can be overriden with a local.yml somewhere.
https://github.com/robert4man/vagrant-oucsdev/blob/master/provisioning/vars/default.yml 

Just remember to add the local override file to a git ignore pattern so it remains truly local.
